//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Stationeers : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ToggleInventory
        {
            get
            {
                return SteamVR_Actions.stationeers_ToggleInventory;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleMenu
        {
            get
            {
                return SteamVR_Actions.stationeers_ToggleMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean MouseControl
        {
            get
            {
                return SteamVR_Actions.stationeers_MouseControl;
            }
        }
        
        public virtual SteamVR_Action_Boolean UseLeft
        {
            get
            {
                return SteamVR_Actions.stationeers_UseLeft;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PitchAndYaw
        {
            get
            {
                return SteamVR_Actions.stationeers_PitchAndYaw;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseL
        {
            get
            {
                return SteamVR_Actions.stationeers_PoseL;
            }
        }
        
        public virtual SteamVR_Action_Pose PoseR
        {
            get
            {
                return SteamVR_Actions.stationeers_PoseR;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ContextScroll
        {
            get
            {
                return SteamVR_Actions.stationeers_ContextScroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.stationeers_Grab;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Walk
        {
            get
            {
                return SteamVR_Actions.stationeers_Walk;
            }
        }
        
        public virtual SteamVR_Action_Boolean UseRight
        {
            get
            {
                return SteamVR_Actions.stationeers_UseRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.stationeers_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.stationeers_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jetpack
        {
            get
            {
                return SteamVR_Actions.stationeers_Jetpack;
            }
        }
        
        public virtual SteamVR_Action_Boolean Ascend
        {
            get
            {
                return SteamVR_Actions.stationeers_Ascend;
            }
        }
        
        public virtual SteamVR_Action_Boolean Descend
        {
            get
            {
                return SteamVR_Actions.stationeers_Descend;
            }
        }
        
        public virtual SteamVR_Action_Boolean ClickModifier
        {
            get
            {
                return SteamVR_Actions.stationeers_ClickModifier;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.stationeers_Haptic;
            }
        }
    }
}
