//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_LaserPointers p_LaserPointers;
        
        private static SteamVR_Input_ActionSet_Stationeers p_Stationeers;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_LaserPointers LaserPointers
        {
            get
            {
                return SteamVR_Actions.p_LaserPointers.GetCopy<SteamVR_Input_ActionSet_LaserPointers>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Stationeers Stationeers
        {
            get
            {
                return SteamVR_Actions.p_Stationeers.GetCopy<SteamVR_Input_ActionSet_Stationeers>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_LaserPointers = ((SteamVR_Input_ActionSet_LaserPointers)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_LaserPointers>("/actions/LaserPointers")));
            SteamVR_Actions.p_Stationeers = ((SteamVR_Input_ActionSet_Stationeers)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Stationeers>("/actions/Stationeers")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.LaserPointers,
                    SteamVR_Actions.Stationeers};
        }
    }
}
